version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.8
    - 2.5.9
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
  - dependency-name: y18n
    versions:
    - 4.0.1
